NotImplementedError: Operator aten.unbind.int does not have a sharding strategy registered.
Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

ghstack-source-id: af6f7a2c960c65026105b25ec8e0ea69e3d89140
Pull Request resolved: https://github.com/pytorch/pytorch/pull/137649